<?php
$this->widget('zii.widgets.CMenu',array(
    'items'=>array(
        array('label'=>'<img src="'.$this->getTemplate('backend').'images/database.png" alt="'.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Database').'"/><span>'.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Database').'</span>',           'url'=>array('/main/database'),     'active'=>$this->action->id=='database',    'visible'=>Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>'<img src="'.$this->getTemplate('backend').'images/themes.png" alt="'.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Themes').'"/><span>'.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Themes').'</span>',                 'url'=>array('/main/themes'),       'active'=>$this->action->id=='themes',      'visible'=>Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>'<img src="'.$this->getTemplate('backend').'images/research.png" alt="'.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'SEO').'"/><span>'.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'SEO').'</span>',                     'url'=>array('/main/seo'),          'active'=>$this->action->id=='seo',         'visible'=>Yii::app()->getUser()->checkAccess('administrator') || Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>'<img src="'.$this->getTemplate('backend').'images/download.png" alt="'.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Files').'"/><span>'.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Files').'</span>',                 'url'=>array('/main/files'),        'active'=>$this->action->id=='files',       'visible'=>Yii::app()->getUser()->checkAccess('administrator') || Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>'<img src="'.$this->getTemplate('backend').'images/gtk-refresh.png" alt="'.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Reset').'"/><span>'.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Reset').'</span>',              'url'=>array('/main/reset'),        'active'=>$this->action->id=='reset',       'visible'=>Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>'<img src="'.$this->getTemplate('backend').'images/currency.png" alt="'.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Prices').'"/><span>'.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Prices').'</span>',               'url'=>array('/main/prices'),       'active'=>$this->action->id=='prices',      'visible'=>Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>'<img src="'.$this->getTemplate('backend').'images/mmotop.png" alt="'.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'MMOTOP').'"/><span>'.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'MMOTOP').'</span>',                 'url'=>array('/main/mmotop'),       'active'=>$this->action->id=='mmotop',      'visible'=>Yii::app()->getUser()->checkAccess('administrator') || Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>'<img src="'.$this->getTemplate('backend').'images/ipb.png" alt="'.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'IPB').'"/><span>'.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'IPB').'</span>',                          'url'=>array('/main/ipb'),          'active'=>$this->action->id=='ipb',         'visible'=>Yii::app()->getUser()->checkAccess('administrator') || Yii::app()->getUser()->checkAccess('super-administrator')),
    ),
    'encodeLabel'=>false,
)); ?>