----- ADMIN TABLE

CREATE TABLE FAI_ADM_GROUP(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	name NVARCHAR(50) NOT NULL,
	password NVARCHAR(50) NOT NULL,
	photo NVARCHAR(255) NOT NULL,
	status NVARCHAR(50) NOT NULL,
	access INT NOT NULL
);


----- NEWS TABLE

CREATE TABLE FAI_en_NEWS(
	id  INT NOT NULL IDENTITY PRIMARY KEY,
	title NVARCHAR(100) NOT NULL,
	meta_desc NVARCHAR(255) NOT NULL,
	meta_key NVARCHAR(255) NOT NULL,
	img NVARCHAR(255) NOT NULL,
	url NVARCHAR(255) NOT NULL,
	s_desc NTEXT NOT NULL,
	f_desc NTEXT NOT NULL,
	date INT NOT NULL,
	author NVARCHAR(50) NOT NULL,
	active INT NOT NULL
);

CREATE TABLE FAI_ru_NEWS(
	id  INT NOT NULL IDENTITY PRIMARY KEY,
	title NVARCHAR(100) NOT NULL,
	meta_desc NVARCHAR(255) NOT NULL,
	meta_key NVARCHAR(255) NOT NULL,
	img NVARCHAR(255) NOT NULL,
	url NVARCHAR(255) NOT NULL,
	s_desc NTEXT NOT NULL,
	f_desc NTEXT NOT NULL,
	date INT NOT NULL,
	author NVARCHAR(50) NOT NULL,
	active INT NOT NULL
);


---- ALTER AccountCharacter

ALTER TABLE AccountCharacter ADD CONSTRAINT pk_Id PRIMARY KEY (Id)


---- ALTER MEMB_INFO

ALTER TABLE MEMB_INFO ADD reg_date INT NULL;
ALTER TABLE MEMB_INFO ADD status VARCHAR(100) NULL;
ALTER TABLE MEMB_INFO ADD user_ip NVARCHAR(15);
ALTER TABLE MEMB_INFO ADD Credits INT;
ALTER TABLE MEMB_INFO ADD web_credits INT;
ALTER TABLE MEMB_INFO ADD usr_avatar NVARCHAR(255);
ALTER TABLE MEMB_INFO ADD usr_bantime INT;
ALTER TABLE MEMB_INFO ADD usr_country NVARCHAR(30);
ALTER TABLE MEMB_INFO ADD usr_city NVARCHAR(30);
ALTER TABLE MEMB_INFO ADD usr_gender NVARCHAR(10);
ALTER TABLE MEMB_INFO ADD usr_signature NTEXT;
UPDATE MEMB_INFO SET memb_name = '';
ALTER TABLE MEMB_INFO ADD CONSTRAINT pk_Name PRIMARY KEY (Name)


---- MMOTOP TABLE

CREATE TABLE FAI_MMOTOP(
	id  INT NOT NULL IDENTITY PRIMARY KEY,
	vote_id INT NULL,
	vote_acc NVARCHAR(20) NULL,
	vote_date INT NULL,
	vote_type INT NULL,
	vote_ip NVARCHAR(15) NULL,
);


---- TICKETS TABLE

CREATE TABLE FAI_TICKETS(
	id  INT NOT NULL IDENTITY PRIMARY KEY,
	memb___id NVARCHAR(20) NULL,
	character NVARCHAR(20) NULL,
	topic NVARCHAR(50) NULL,
	description NTEXT NULL,
	date INT NULL,
	ip NVARCHAR(15) NULL,
	status INT NULL,
	priority INT NULL,
);


---- ABOUT TABLE

CREATE TABLE FAI_en_ABOUT(
	id INT NOT NULL IDENTITY PRIMARY KEY,
	title NVARCHAR(50) NULL,
	description NTEXT NULL,
	meta_key NVARCHAR(255) NULL,
	meta_desc NVARCHAR (255) NULL,
	date INT NULL,
	status INT NULL,
	onmpage INT NULL,
);

CREATE TABLE FAI_ru_ABOUT(
	id INT NOT NULL IDENTITY PRIMARY KEY,
	title NVARCHAR(50) NULL,
	description NTEXT NULL,
	meta_key NVARCHAR(255) NULL,
	meta_desc NVARCHAR (255) NULL,
	date INT NULL,
	status INT NULL,
	onmpage INT NULL,
);


---- CP HOME TABLE

CREATE TABLE FAI_en_CP_HOME(
	id INT NOT NULL IDENTITY PRIMARY KEY,
	title NVARCHAR(50) NULL,
	img NVARCHAR(255) NULL,
	s_desc NTEXT NULL,
	description NTEXT NULL,
	date INT NULL,
	author NVARCHAR(20) NULL,
	status INT NULL,
);

CREATE TABLE FAI_ru_CP_HOME(
	id INT NOT NULL IDENTITY PRIMARY KEY,
	title NVARCHAR(50) NULL,
	img NVARCHAR(255) NULL,
	s_desc NTEXT NULL,
	description NTEXT NULL,
	date INT NULL,
	author NVARCHAR(20) NULL,
	status INT NULL,
);


----- TICKETS POSTS

CREATE TABLE FAI_TICKETS_POST(
	id INT IDENTITY PRIMARY KEY,
	ticket_id INT,
	message NTEXT,
	date INT,
	name NVARCHAR(20),
	ip NVARCHAR(15),
	photo NVARCHAR(255)
);

INSERT INTO FAI_ADM_GROUP (name,password,photo,status,access,rname) VALUES ('admin','36c951ca6bb5bbe84d3bc07ca8d1a030','','super-administrator','1','Sergey');
ALTER TABLE Character ADD Grand_Reset INT;

ALTER TABLE FAI_ADM_GROUP ADD rname NVARCHAR(20);
UPDATE FAI_ADM_GROUP SET rname = 'Sergey' WHERE name = 'admin';
ALTER TABLE FAI_TICKETS_POST ADD sender INT;
ALTER TABLE FAI_TICKETS_POST ADD upd_type INT;




---- MEMB_CREDITS

IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[MEMB_CREDITS]')
AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
DROP TABLE [dbo].[MEMB_CREDITS];
CREATE TABLE [dbo].[MEMB_CREDITS] (
	memb___id NVARCHAR(10) NOT NULL,
    credits INT NOT NULL,
    used INT NOT NULL,
);


---- FILES

CREATE TABLE FAI_FILES(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	title NVARCHAR(50) NOT NULL,
	description NVARCHAR(100) NOT NULL,
	link NVARCHAR(255) NOT NULL,
);


---- FAQ

CREATE TABLE FAI_ru_FAQ(
  id INT NOT NULL PRIMARY KEY IDENTITY,
  title NVARCHAR(50) NOT NULL,
  meta_desc NVARCHAR(255) NOT NULL,
  meta_key NVARCHAR(255) NOT NULL,
  description NTEXT NOT NULL,
  link NVARCHAR(255) NOT NULL,
  date INT NOT NULL
);



---- FAICORE BAN TABLE

CREATE TABLE FAI_ru_BAN(
  id INT NOT NULL PRIMARY KEY IDENTITY,
  memb___id NVARCHAR(50) NOT NULL,
  reason NVARCHAR(100) NOT NULL,
  who NVARCHAR(30) NOT NULL,
  ban_time INT NOT NULL,
  date INT NOT NULL,
);

CREATE TABLE FAI_en_BAN(
  id INT NOT NULL PRIMARY KEY IDENTITY,
  memb___id NVARCHAR(50) NOT NULL,
  reason NVARCHAR(100) NOT NULL,
  who NVARCHAR(30) NOT NULL,
  ban_time INT NOT NULL,
  date INT NOT NULL,
);






