<?php
$this->widget('zii.widgets.CMenu',array(
    'htmlOptions'=>array('class'=>'nav'),
    'items'=>array(
        array('label'=>''.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Settings').'',         'url'=>array('/main/index'),'itemOptions'=>array('class'=>'home'), 'active' => Yii::app()->controller->getId() == 'main', 'visible'=>Yii::app()->getUser()->checkAccess('administrator') || Yii::app()->getUser()->checkAccess('moderator') || Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>''.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'News').'',             'url'=>array('/news/index'), 'itemOptions'=>array('class'=>'news') , 'active' => Yii::app()->controller->getId() == 'news', 'visible'=>Yii::app()->getUser()->checkAccess('administrator') || Yii::app()->getUser()->checkAccess('moderator') || Yii::app()->getUser()->checkAccess('journalist') || Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>''.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'File manager').'',     'url'=>array('/files/index'), 'itemOptions'=>array('class'=>'files') , 'active' => Yii::app()->controller->getId() == 'files', 'visible'=>Yii::app()->getUser()->checkAccess('administrator') || Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>''.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Rankings').'',         'url'=>array('/rankings/index'), 'itemOptions'=>array('class'=>'rankings'), 'active' => Yii::app()->controller->getId() == 'rankings', 'visible'=>Yii::app()->getUser()->checkAccess('administrator') || Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>''.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Users ').'',           'url'=>array('/users/index'), 'itemOptions'=>array('class'=>'users'), 'active' => Yii::app()->controller->getId() == 'users', 'visible'=>Yii::app()->getUser()->checkAccess('administrator') || Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>''.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'User account').'',     'url'=>array('/usercp/index'), 'itemOptions'=>array('class'=>'usercp'), 'active' => Yii::app()->controller->getId() == 'usercp', 'visible'=>Yii::app()->getUser()->checkAccess('administrator') || Yii::app()->getUser()->checkAccess('moderator') || Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>''.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Payment Methods').'',  'url'=>array('/payment/index'), 'itemOptions'=>array('class'=>'payment'), 'active' => Yii::app()->controller->getId() == 'payment', 'visible'=>Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>''.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Tickets').'',          'url'=>array('/tickets/index'), 'itemOptions'=>array('class'=>'tickets'), 'active' => Yii::app()->controller->getId() == 'tickets', 'visible'=>Yii::app()->getUser()->checkAccess('administrator') || Yii::app()->getUser()->checkAccess('moderator') || Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>''.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Staff').'',            'url'=>array('/staff/index'), 'itemOptions'=>array('class'=>'staff'), 'active' => Yii::app()->controller->getId() == 'staff', 'visible'=>Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>''.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'About Us').'',         'url'=>array('/about/index'), 'itemOptions'=>array('class'=>'about'), 'active' => Yii::app()->controller->getId() == 'about', 'visible'=>Yii::app()->getUser()->checkAccess('administrator') || Yii::app()->getUser()->checkAccess('super-administrator')),
        array('label'=>''.Yii::t(''.Yii::app()->request->cookies['language']->value.'', 'Logs').'',             'url'=>array('/logs/index'), 'itemOptions'=>array('class'=>'logs'), 'active' => Yii::app()->controller->getId() == 'logs', 'visible'=>Yii::app()->getUser()->checkAccess('administrator') || Yii::app()->getUser()->checkAccess('super-administrator'))
    ),
));
